# Python 程式偵錯

+ Syntax Errors 語法錯誤
 + 該行語法錯誤，Python 無法編譯執行。
 + 修正語法錯誤
+ Exception 例外
 + 語法撰寫上沒有錯誤，執行時因資料邏輯或外部系統狀態發生錯誤， Python 會引發例外(Exception) 
 + 如果例外沒有被處理而傳遞到Python直譯器，程式中斷執行

In [6]:
num1 = 10
num2 = 0
try:
    print(num1 / num2)
except:
    print("分母不可為0")

分母不可為0


## Numpy
+ 可做到的功能
  + 快速的多維陣列操作。
  + 可靠的科學功能函數庫。
  + 可協助繪圖工具進行繪圖。
+ NumPy 是幾乎每個科學 Python 應用程序或模組的核心，它提供了以向量化形式的快速 N-d 陣列類型可供操作。

In [9]:
import numpy as np
list1 = [1,2,3]
list2 = [8,4,7]
print(list1 + list2)

a = np.array(list1)
b = np.array(list2)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[1, 2, 3, 8, 4, 7]
[ 9  6 10]
[-7 -2 -4]
[ 8  8 21]
[0.125      0.5        0.42857143]


## 陣列附加資料

In [10]:
import numpy as np
a = np.array([1,3,5,7,9])
b = np.append(a,[10,11,12,18])
print(b)

[ 1  3  5  7  9 10 11 12 18]


## 陣列插入資料

In [14]:
import numpy as np
a = np.array([1,3,5,7,9])
b = np.insert(a,2,[11,18])
print(b)


[ 1  3 11 18  5  7  9]


## 陣列刪除資料

In [15]:
import numpy as np
a = np.array([1,3,5,7,9])
b = np.delete(a,2)
print(b)

[1 3 7 9]


## 下載紫外線指數練習

In [16]:
import requests
API_KEY = "rdec-key-123-45678-011121314"
url = f"https://opendata.cwa.gov.tw/api/v1/rest/datastore/O-A0005-001?Authorization={API_KEY}"
print(url)

https://opendata.cwa.gov.tw/api/v1/rest/datastore/O-A0005-001?Authorization=rdec-key-123-45678-011121314


In [27]:
import requests
resp = requests.get(url)#下載檔案
resp.encoding = "utf-8" #給予編碼
jsonData = resp.json()#將檔案轉會為JSON
print(type(jsonData))
records =  jsonData["records"]
print(type(records))
print(records)
weatherElement = records["weatherElement"]
print(weatherElement["elementName"])
location = weatherElement["location"]
print(type(location))
#print(location)
for v in location:
    print(v["StationID"],v["UVIndex"])

<class 'dict'>
<class 'dict'>
{'weatherElement': {'elementName': '氣象站每日紫外線指數最大值', 'location': [{'StationID': '467350', 'UVIndex': 3.0}, {'StationID': '467270', 'UVIndex': 5.0}, {'StationID': '467110', 'UVIndex': 4.0}, {'StationID': '467300', 'UVIndex': 4.0}, {'StationID': '466940', 'UVIndex': 3.0}, {'StationID': '466950', 'UVIndex': 5.0}, {'StationID': '466920', 'UVIndex': 4.0}, {'StationID': '466930', 'UVIndex': 4.0}, {'StationID': '466900', 'UVIndex': 2.0}, {'StationID': '466910', 'UVIndex': 7.0}, {'StationID': '467990', 'UVIndex': 5.0}, {'StationID': '467420', 'UVIndex': 6.0}, {'StationID': '466990', 'UVIndex': 6.0}, {'StationID': '467480', 'UVIndex': 7.0}, {'StationID': '467490', 'UVIndex': 5.0}, {'StationID': '467441', 'UVIndex': 6.0}, {'StationID': '467620', 'UVIndex': 6.0}, {'StationID': '467050', 'UVIndex': 3.0}, {'StationID': '467610', 'UVIndex': 3.0}, {'StationID': '467660', 'UVIndex': 6.0}, {'StationID': '467590', 'UVIndex': 7.0}, {'StationID': '467650', 'UVIndex': 5.0}, {'S

## 氣候預報

In [28]:
import requests
API_KEY = "rdec-key-123-45678-011121314"
url = f"https://opendata.cwa.gov.tw/api/v1/rest/datastore/F-C0032-001?Authorization={API_KEY}&format=JSON&locationName=臺北市&elementName=Wx,MinT,MaxT"
print(url)

https://opendata.cwa.gov.tw/api/v1/rest/datastore/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON&locationName=臺北市&elementName=Wx,MinT,MaxT


In [29]:
def getJson(url):
    resp = requests.get(url)
    resp.encoding = "utf-8"
    data = resp.json()
    return data

In [30]:
getJson(url)

{'success': 'true',
 'result': {'resource_id': 'F-C0032-001',
  'fields': [{'id': 'datasetDescription', 'type': 'String'},
   {'id': 'locationName', 'type': 'String'},
   {'id': 'parameterName', 'type': 'String'},
   {'id': 'parameterValue', 'type': 'String'},
   {'id': 'parameterUnit', 'type': 'String'},
   {'id': 'startTime', 'type': 'Timestamp'},
   {'id': 'endTime', 'type': 'Timestamp'}]},
 'records': {'datasetDescription': '三十六小時天氣預報',
  'location': [{'locationName': '臺北市',
    'weatherElement': [{'elementName': 'Wx',
      'time': [{'startTime': '2024-01-31 12:00:00',
        'endTime': '2024-01-31 18:00:00',
        'parameter': {'parameterName': '多雲', 'parameterValue': '4'}},
       {'startTime': '2024-01-31 18:00:00',
        'endTime': '2024-02-01 06:00:00',
        'parameter': {'parameterName': '晴時多雲', 'parameterValue': '2'}},
       {'startTime': '2024-02-01 06:00:00',
        'endTime': '2024-02-01 18:00:00',
        'parameter': {'parameterName': '晴時多雲', 'parameterValue'

In [31]:
def getParameter(typeStr,data):
    strMsg = ""
    for wx in data:
        strMsg += "開始日期:"+wx["startTime"]
        strMsg += "結束日期:"+wx["endTime"]
        strMsg += typeStr + wx["parameter"]["parameterName"]
    return strMsg   
        

In [37]:
def loadData(locatName):
    if len(locatName) == 0:
        return ""
    url = f"https://opendata.cwa.gov.tw/api/v1/rest/datastore/F-C0032-001?Authorization={API_KEY}&format=JSON&locationName={locatName}&elementName=Wx,MinT,MaxT"
    josnObj = getJson(url)
    location = josnObj["records"]["location"]
    if len(location) == 0:
        return ""
    
    data=""
    for locat in location: 
  
        name = locat['locationName']+":"
        wx = getParameter("氣候狀態:",locat['weatherElement'][0]["time"])          
        mit = getParameter("最低溫度:",locat['weatherElement'][1]["time"])
        mxt = getParameter("最高溫度:",locat['weatherElement'][2]["time"])
        msg = name + wx + mit+mxt
        data+= msg
    return data

In [38]:
loadData("臺北市")

'臺北市:開始日期:2024-01-31 12:00:00結束日期:2024-01-31 18:00:00氣候狀態:多雲開始日期:2024-01-31 18:00:00結束日期:2024-02-01 06:00:00氣候狀態:晴時多雲開始日期:2024-02-01 06:00:00結束日期:2024-02-01 18:00:00氣候狀態:晴時多雲開始日期:2024-01-31 12:00:00結束日期:2024-01-31 18:00:00最低溫度:22開始日期:2024-01-31 18:00:00結束日期:2024-02-01 06:00:00最低溫度:18開始日期:2024-02-01 06:00:00結束日期:2024-02-01 18:00:00最低溫度:18開始日期:2024-01-31 12:00:00結束日期:2024-01-31 18:00:00最高溫度:26開始日期:2024-01-31 18:00:00結束日期:2024-02-01 06:00:00最高溫度:22開始日期:2024-02-01 06:00:00結束日期:2024-02-01 18:00:00最高溫度:26'

## 爬蟲

## BeautifulSoup Base
find() 只找第一個符合條件的

https://www.crummy.com/software/BeautifulSoup/bs4/doc.zh/#find-all

find_all() 找所有符合條件的

select_one() 只找一個符合條件的可直接使用css語法

select() 找所有符合條件的可使用css語法

In [50]:
from bs4 import BeautifulSoup
html='''<a id='a1' class="c1" href="https://google.com">Google</a>
<a id='a2' class="c1"  href="https://yahoo.com">Yahoo</a>
<a id='a3' class="c3" href="https://facebook.com">Facebook</a>
'''
print(html)
soup = BeautifulSoup(html,"html5lib")
print(soup.find(id='a1'))
print(soup.find_all(class_="c1"))

print(soup.find(id='a1').getText())
print(soup.find(id='a1').get('href'))

tmpList = soup.find_all(class_="c1")
for tag in tmpList:
    print(tag.getText(),tag.get("href"))

<a id='a1' class="c1" href="https://google.com">Google</a>
<a id='a2' class="c1"  href="https://yahoo.com">Yahoo</a>
<a id='a3' class="c3" href="https://facebook.com">Facebook</a>

<a class="c1" href="https://google.com" id="a1">Google</a>
[<a class="c1" href="https://google.com" id="a1">Google</a>, <a class="c1" href="https://yahoo.com" id="a2">Yahoo</a>]
Google
https://google.com
Google https://google.com
Yahoo https://yahoo.com


# 使用html檔案練習

In [61]:
import bs4
htmlFile = open('web1.html','r',encoding='utf8',errors='igore')
objSoup = bs4.BeautifulSoup(htmlFile,'html5lib')
#print(objSoup)
objTag = objSoup.find_all('h1')
for data in objTag:
    print(data)
    print(data.getText())

<h1>class與id練習測試h1標籤</h1>
class與id練習測試h1標籤
<h1>國家首都資料表</h1>
國家首都資料表
<h1>h1標籤測試1</h1>
h1標籤測試1
<h1>h1標籤測試2</h1>
h1標籤測試2
<h1>h1標籤測試3</h1>
h1標籤測試3
<h1>h1標籤測試4</h1>
h1標籤測試4


In [66]:
import bs4
htmlFile = open('web1.html','r',encoding='utf8',errors='igore')
objSoup = bs4.BeautifulSoup(htmlFile,'html5lib')
objTag = objSoup.find_all(class_='class1',limit=3)
for data in objTag:
    print(data)
    print(data.getText())

<li class="class1">Foo</li>
Foo
<li class="class1">Bar</li>
Bar
<li class="class1">Jay</li>
Jay
